### PR TITLE
Ehougaard branch

### PR DESCRIPTION
**Pull request by hugoasouza**
For development practicing purpose and following videos from Erik Hougaard i decided to create this Yahtzee Game (Solo).

**Bad version number:**
I started calling it **Version 1** then 1.2, when i saw it was half-baked then i just decided to call it 0.8.#

**Identified bug(s):**
- Game board should start in Edit mode, it is starting in View mode only then user need to enable edition.

### CODE REVIEW

**Review by hougaard — COMMENTED** [review]
Please move it into the **ViewerSubmissions** folder :)

**Comment by hugoasouza** [comment]
I am new to AL and also new to Git, i am trying to discover how to make this move :)

**Comment by hougaard** [comment]
Create a folder called ViewerSubmissions and move your YahtzeeGame folder into that.

**Comment by hugoasouza** [comment]
Thank you very much, Erik. Not just for merging this code but specially for teaching so well. 
One month ago i did not know anything about AL and BC. Your videos were essential for my learning and practicing.

**Pull request merged**
